name: test-snapshots

on:
  workflow_dispatch:    
  schedule:
    - cron: '0 5 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: run tests
        run: dotnet test -c release --filter snapshot --logger="junit;LogFilePath=TestResults/results.xml" service/
        env:
          SNAPSHOOTER_STRICT_MODE: true

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.6
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: service/**/TestResults/*.xml
