name: Validate

on:
  pull_request:
    branches: [$default-branch]

jobs:
  validate:
    name: Validate code base
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build service/ --file service/Dockerfile --tag jholm117/recipe.md
